# site settings
title: Chinmay Badjatya
email: badjatyachinmay@gmail.com
description: I see you've found my portfolio. Here, I talk about my projects and blog about tech I'm lately obsessed with. Go ahead, check it out!
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Chinmay Badjatya

# homepage tiles
#tiles-source: pages # accepts "posts" or "pages"
#tiles-count: 6

# social settings
github_url: https://github.com/Chinmay4400
linkedin_url: https://www.linkedin.com/in/chinmay-badjatya-675a10162
twitter_url: https://twitter.com/Chinmay4400

# build settings
markdown: kramdown

sass:
  style: compressed
